
<div class="stop-float"></div>
<div id="content-menu">
	
	<div id="menu">
	<ul class="menu-onglet">
		<?php
		
			foreach($this->content_onglets as $nom => $donnees){
				echo "<li><a href='".$this->baseUrl($donnees['baseurl'])."?ajax=1'>".$nom."</a>";
				if(isset($donnees['sous_menu'])){
					echo '<ul class="sous-menu">';
					foreach($donnees['sous_menu'] as $nom_sous_menu => $url_sous_menu){
						echo "<li><a href='".$this->baseUrl($url_sous_menu)."?ajax=1'>".$nom_sous_menu."</a></li>";
					}
					echo "</ul>";
				}
				echo "</li>";
			}
		
		?>
	</ul>
	</div>
	
	<div id="content-ajax">
		<div>Cliquez sur un des onglets ci-dessus pour accéder au service désiré. Si vous pensez qu'un onglet est manquant, veuillez contacter votre chef de service pour que nous puissions vous attribuer de nouveaux droits.</div>
	</div>
</div>