<div id="content-block-connecte">
	<?php 
		echo $this->action('cadreconnecte', 'intranet');
	?>
</div>
<div class="stop-float"></div>
<div id="content-menu">
	<ul class="menu-onglet">
		<?php
		
			foreach($this->content_onglets as $nom => $chaine_baseurl){
				echo "<li><a href='".$this->baseUrl($chaine_baseurl)."?ajax=1'>".$nom."</a></li>";
			}
		
		?>
	</ul>
	
	<div id="content-ajax">
		<div>Cliquez sur un des onglets ci-dessus pour accéder au service désiré. Si vous pensez qu'un onglet est manquant, veuillez contacter votre chef de service pour que nous puissions vous attribuer de nouveaux droits.</div>
	</div>
</div>