<link href="<?php echo $this->baseUrl(); ?>/css/jquery-ui.css" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.8.3.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/timepicker.js"></script>
	<script>
	$(document).ready(function(){
		$(function() {
		$( "#date_effective" ).datepicker();
		});
	});
	</script>
<?php

echo $this->form_maintenance_validation;

if($this->Done == true)
{
	echo 'Modification effectué dans la base de donnée';
}
