

<link href="<?php echo $this->baseUrl(); ?>/css/jquery-ui.css" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.8.3.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui-timepicker-addon.js"></script>
	<script>
	$(document).ready(function(){
		$(function() {
		$('#date_expiration').datepicker();
		});
	});
    </script>
    
<?php


 echo $this->form_ajoutbrevet;
 