<link href="<?php echo $this->baseUrl(); ?>/css/jquery-ui.css" media="screen" rel="stylesheet" type="text/css">
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.8.3.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui.js"></script>
<script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui-timepicker-addon.js"></script>
	<script>
	$(document).ready(function(){
		$(function() {
		$('#date_vol_depart').datetimepicker();
		$('#date_vol_arrive').datetimepicker();
		});
	});
    
	$(document).ready(function(){
		$(function() {
    	var idpilote = $('#id_pilote option:selected').val();
    	//$('#id_copilote').remove($('#id_pilote option:selected').text());
    	$("#id_copilote option[value='" + idpilote + "']").remove();  
		});
	});
	
    </script>
    
<?php
 echo $this->form_vol;
if($this->Done == true)
{
	echo 'Ajout effectué dans la base de donnée';
}
 